### ISSUE TITLE
Bugs: Icon not appeared in task bar & Font not displayed & Restart button not work when stopwatch running & Fullscreen icon in title bar not become 'windowed'

### ISSUE THREAD

**Issue by NoNormalCreeper** [S0KPiseth/MultiTimer#2]
1. After launch the progarm, there's no icon of MultiTimer in the task bar, which makes it hard to stop the program sometimes.
2. The font `Roboto mono` used in the UI can't be rendered correctly, because most users haven't this font installed in their devices.
3. When the stopwatch is running, clicking the restart button is no use.
4. When it's in fullscreen mode, it's expected to show an 'windowed' button in the title bar, instead of keeping showing 'fullscreen'.

I'll be glad if you could give me an oppotunity to open a pull request to fix these bugs :)

**Comment by NoNormalCreeper** [comment]
5. The dark mode switch disappears in the 'Stopwatch' tab.

**Comment by NoNormalCreeper** [comment]
6. The timer will have an extra second.
For example, set a timer of `2` min `5` s, and you will see how this problem happens:

2:05
2:04
2:03
2:02
2:01
**2:00**
**1:60**
1:59
1:58
1:57
......

The `1:60` is the extra second.

**Comment by S0KPiseth** [comment]
Thank you for reporting the issues.
For 3, I want the user to stop the stopwatch first before they can reset it, and for 5, the stopwatch tab is still under consideration of adding more functions or not because I don't want it to be too overwhelming and keep it as minimalist as possible. But yeah, feel free to open any pull request with your proposed fixes.

**Comment by NoNormalCreeper** [comment]
Thanks for your reply! I will try to fix 1, 2, 4 and 6.
But for 3, I think the following is a better idea: when the stopwatch is running, hide the 'reset' button, and make the 'stop' button a bigger one, just like the 'start' button. This may let the user know that they should stop the stopwatch first before they can reset it, or users (like me) may misunderstand that the stopwatch can be reset when running.
